[theme]
primaryColor = "#81b29a"
backgroundColor = "#fafaf8"
secondaryBackgroundColor = "#f5f4f0"
textColor = "#1a1a2e"
font = "sans serif"

[server]
maxUploadSize = 5

[client]
showErrorDetails = false
